name: Hola Mundo

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hello world"
  other:
    runs-on: ubuntu-latest
    needs: [hello]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: LS
        run: ls -al
