name: Hola Mundo

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hello world"
  other:
    runs-on: ubuntu-latest
    needs: [hello]
    steps:
      - name: LS
        run: ls -al
