name: Test composite
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hello world"
  other:
    runs-on: ubuntu-latest
    needs: [hello]
    env:
      MY_VAR: 103858532HLKSLF
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: LS
        run: ls -al
      - name: Run envs
        run: echo "$MY_VAR $INTERN_STEP_VAR ${{vars.MY_GITHUB_VAR}}"
        env:
          INTERN_STEP_VAR: 12345
      - name: Run secrets
        run: echo "Secrets ${{secrets.SECRET_KEY}}"
      - name: Create text file
        uses: ./.github/actions/my-action
        with:
          message: Juan Camilo
